# Generated by Django 3.2 on 2021-04-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210414_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dateissued',
            new_name='date_issued',
        ),
        migrations.AddField(
            model_name='employee',
            name='line_manager_staff_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Line_Manager ID Number'),
        ),
    ]
