# Generated by Django 3.2 on 2021-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210414_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Name_of_relief_person',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Delegation_of_Authority(DOA)'),
        ),
    ]
