# Generated by Django 3.2 on 2021-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_name_of_relief_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Name_of_relief_person',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Delegation of Authority(DOA)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='line_manager_staff_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Line Manager ID Number'),
        ),
    ]
